### ISSUE TITLE
访问失败

### ISSUE THREAD

**Issue by zuobiao-zhou** [bupticybee/ByrBbsMirror#1]
老哥，现在貌似访问不了了捏

**Comment by bupticybee** [comment]
> 老哥，现在貌似访问不了了捏

现在论坛封锁的更严格啦，这个方法已经无法绕过封锁了

**Comment by bupticybee** [comment]
> 老哥，现在貌似访问不了了捏

能够一直苟到现在我已经很满意了，之后我们的互联网政策肯定是越来越严苛的
